const actionTypes = {
  SAVE_COURSE_SUCCESS: "SAVE_COURSE_SUCCESS",
  UPDATE_COURSE_SUCCESS: "UPDATE_COURSE_SUCCESS",
  LOAD_COURSES_SUCCESS: "LOAD_COURSES_SUCCESS",
  LOAD_AUTHORS_SUCCESS: "LOAD_AUTHORS_SUCCESS"
};

export default actionTypes;
