const actionTypes = {
  BEGIN_AJAX_CALL: "BEGIN_AJAX_CALL",
  AJAX_CALL_ERROR: "AJAX_CALL_ERROR",
  SAVE_COURSE_SUCCESS: "SAVE_COURSE_SUCCESS",
  UPDATE_COURSE_SUCCESS: "UPDATE_COURSE_SUCCESS",
  LOAD_COURSES_SUCCESS: "LOAD_COURSES_SUCCESS",
  LOAD_AUTHORS_SUCCESS: "LOAD_AUTHORS_SUCCESS"
};

export default actionTypes;
